#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Jina_Head

#include "Basic.hpp"

#include "ABP_Base_Head_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_Jina_Head.ABP_Jina_Head_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0108 - 0x0108)
struct ABP_Jina_Head::FAnimBlueprintGeneratedConstantData final  : public ABP_Base_Head::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(ABP_Jina_Head::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ABP_Jina_Head::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ABP_Jina_Head::FAnimBlueprintGeneratedConstantData) == 0x000108, "Wrong size on ABP_Jina_Head::FAnimBlueprintGeneratedConstantData");

}

