#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Female_Hair_Bob01

#include "Basic.hpp"

#include "ABP_Female_Hair_Medium_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Female_Hair_Bob01.ABP_Female_Hair_Bob01_C
// 0x0000 (0x29A0 - 0x29A0)
class UABP_Female_Hair_Bob01_C final  : public UABP_Female_Hair_Medium_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_Female_Hair_Bob01_C">();
	}
	static class UABP_Female_Hair_Bob01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Female_Hair_Bob01_C>();
	}
};
static_assert(alignof(UABP_Female_Hair_Bob01_C) == 0x000010, "Wrong alignment on UABP_Female_Hair_Bob01_C");
static_assert(sizeof(UABP_Female_Hair_Bob01_C) == 0x0029A0, "Wrong size on UABP_Female_Hair_Bob01_C");

}

