#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CinematicValeriaCharacter_Female

#include "Basic.hpp"

#include "BP_ValeriaCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CinematicValeriaCharacter_Female.BP_CinematicValeriaCharacter_Female_C
// 0x0000 (0x1740 - 0x1740)
class ABP_CinematicValeriaCharacter_Female_C final  : public ABP_ValeriaCharacter_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CinematicValeriaCharacter_Female_C">();
	}
	static class ABP_CinematicValeriaCharacter_Female_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CinematicValeriaCharacter_Female_C>();
	}
};
static_assert(alignof(ABP_CinematicValeriaCharacter_Female_C) == 0x000010, "Wrong alignment on ABP_CinematicValeriaCharacter_Female_C");
static_assert(sizeof(ABP_CinematicValeriaCharacter_Female_C) == 0x001740, "Wrong size on ABP_CinematicValeriaCharacter_Female_C");

}

