#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PregamePlayerController

#include "Basic.hpp"

#include "Palia_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PregamePlayerController.BP_PregamePlayerController_C
// 0x0010 (0x0A48 - 0x0A38)
class ABP_PregamePlayerController_C final  : public AVAL_PlayerControllerBase
{
public:
	FMulticastInlineDelegateProperty_             OnToggleChat;                                      // 0x0A38(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void OnToggleChat__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PregamePlayerController_C">();
	}
	static class ABP_PregamePlayerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PregamePlayerController_C>();
	}
};
static_assert(alignof(ABP_PregamePlayerController_C) == 0x000008, "Wrong alignment on ABP_PregamePlayerController_C");
static_assert(sizeof(ABP_PregamePlayerController_C) == 0x000A48, "Wrong size on ABP_PregamePlayerController_C");
static_assert(offsetof(ABP_PregamePlayerController_C, OnToggleChat) == 0x000A38, "Member 'ABP_PregamePlayerController_C::OnToggleChat' has a wrong offset!");

}

