#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_ShowKeyRebindResultTips

#include "Basic.hpp"

#include "BPI_ShowKeyRebindResultTips_classes.hpp"
#include "BPI_ShowKeyRebindResultTips_parameters.hpp"


namespace SDK
{

// Function BPI_ShowKeyRebindResultTips.BPI_ShowKeyRebindResultTips_C.RefreshKeyRebindTips
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKeyRebind_DisplayResult         KeyRebindResultInfo                                    (BlueprintVisible, BlueprintReadOnly, Parm)

void IBPI_ShowKeyRebindResultTips_C::RefreshKeyRebindTips(const struct FKeyRebind_DisplayResult& KeyRebindResultInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_ShowKeyRebindResultTips_C", "RefreshKeyRebindTips");

	Params::BPI_ShowKeyRebindResultTips_C_RefreshKeyRebindTips Parms{};

	Parms.KeyRebindResultInfo = std::move(KeyRebindResultInfo);

	UObject::ProcessEvent(Func, &Parms);
}

}

