#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MAP_PreGame

#include "Basic.hpp"

#include "MAP_PreGame_classes.hpp"
#include "MAP_PreGame_parameters.hpp"


namespace SDK
{

// Function MAP_PreGame.MAP_PreGame_C.GetCharacterInventoryPreviewer
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AVAL_CharacterPreviewer*          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class AVAL_CharacterPreviewer* AMAP_PreGame_C::GetCharacterInventoryPreviewer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_PreGame_C", "GetCharacterInventoryPreviewer");

	Params::MAP_PreGame_C_GetCharacterInventoryPreviewer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_PreGame.MAP_PreGame_C.GetCharacterPreviewer
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AVAL_CharacterPreviewer*          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FTransform                       CallFunc_MakeTransform_ReturnValue                     (IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue  (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ABP_CharacterPreview_C*           CallFunc_FinishSpawningActor_ReturnValue               (ZeroConstructor, NoDestructor, HasGetValueTypeHash)

class AVAL_CharacterPreviewer* AMAP_PreGame_C::GetCharacterPreviewer(bool CallFunc_IsValid_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_CharacterPreview_C* CallFunc_FinishSpawningActor_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_PreGame_C", "GetCharacterPreviewer");

	Params::MAP_PreGame_C_GetCharacterPreviewer Parms{};

	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;
	Parms.CallFunc_MakeTransform_ReturnValue = std::move(CallFunc_MakeTransform_ReturnValue);
	Parms.CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue = CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue;
	Parms.CallFunc_FinishSpawningActor_ReturnValue = CallFunc_FinishSpawningActor_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_PreGame.MAP_PreGame_C.GetCharacterRenderStudio
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AVAL_CharacterRenderStudio*       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class AVAL_CharacterRenderStudio* AMAP_PreGame_C::GetCharacterRenderStudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_PreGame_C", "GetCharacterRenderStudio");

	Params::MAP_PreGame_C_GetCharacterRenderStudio Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_PreGame.MAP_PreGame_C.GetItemPreviewerSpawnLocation
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector AMAP_PreGame_C::GetItemPreviewerSpawnLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_PreGame_C", "GetItemPreviewerSpawnLocation");

	Params::MAP_PreGame_C_GetItemPreviewerSpawnLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_PreGame.MAP_PreGame_C.GetLobbyCharacter
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AValeriaCharacter*                ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class AValeriaCharacter* AMAP_PreGame_C::GetLobbyCharacter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_PreGame_C", "GetLobbyCharacter");

	Params::MAP_PreGame_C_GetLobbyCharacter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_PreGame.MAP_PreGame_C.GetRenderStudioSpawnLocation
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector AMAP_PreGame_C::GetRenderStudioSpawnLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_PreGame_C", "GetRenderStudioSpawnLocation");

	Params::MAP_PreGame_C_GetRenderStudioSpawnLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

