#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MAP_CharacterRender_LevelInstance_4

#include "Basic.hpp"

#include "MAP_CharacterRender_LevelInstance_4_classes.hpp"
#include "MAP_CharacterRender_LevelInstance_4_parameters.hpp"


namespace SDK
{

// Function MAP_CharacterRender_LevelInstance_4.MAP_CharacterRender_C.ExecuteUbergraph_MAP_CharacterRender
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMAP_CharacterRender_C::ExecuteUbergraph_MAP_CharacterRender(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_CharacterRender_C", "ExecuteUbergraph_MAP_CharacterRender");

	Params::MAP_CharacterRender_C_ExecuteUbergraph_MAP_CharacterRender Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MAP_CharacterRender_LevelInstance_4.MAP_CharacterRender_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMAP_CharacterRender_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_CharacterRender_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MAP_CharacterRender_LevelInstance_4.MAP_CharacterRender_C.GetAllCameraActors
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TSet<class AActor*>                     ReturnValue                                            (Parm, OutParm, ReturnParm)

TSet<class AActor*> AMAP_CharacterRender_C::GetAllCameraActors() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_CharacterRender_C", "GetAllCameraActors");

	Params::MAP_CharacterRender_C_GetAllCameraActors Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_CharacterRender_LevelInstance_4.MAP_CharacterRender_C.GetAllTaggedActors
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TSet<class AActor*>                     ReturnValue                                            (Parm, OutParm, ReturnParm)

TSet<class AActor*> AMAP_CharacterRender_C::GetAllTaggedActors() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_CharacterRender_C", "GetAllTaggedActors");

	Params::MAP_CharacterRender_C_GetAllTaggedActors Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_CharacterRender_LevelInstance_4.MAP_CharacterRender_C.GetCameraActorForCosmeticAsset
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UVAL_CharacterCustomizationItemBase*Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EVAL_CharacterBodyType                  BodyType                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class AActor* AMAP_CharacterRender_C::GetCameraActorForCosmeticAsset(class UVAL_CharacterCustomizationItemBase* Item, EVAL_CharacterBodyType BodyType) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_CharacterRender_C", "GetCameraActorForCosmeticAsset");

	Params::MAP_CharacterRender_C_GetCameraActorForCosmeticAsset Parms{};

	Parms.Item = Item;
	Parms.BodyType = BodyType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_CharacterRender_LevelInstance_4.MAP_CharacterRender_C.GetCharacter
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class AValeriaCharacter*                ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class AValeriaCharacter* AMAP_CharacterRender_C::GetCharacter() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_CharacterRender_C", "GetCharacter");

	Params::MAP_CharacterRender_C_GetCharacter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MAP_CharacterRender_LevelInstance_4.MAP_CharacterRender_C.GetDefaultCameraActor
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class AActor* AMAP_CharacterRender_C::GetDefaultCameraActor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAP_CharacterRender_C", "GetDefaultCameraActor");

	Params::MAP_CharacterRender_C_GetDefaultCameraActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

