#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MenuHubOtherMenuType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum MenuHubOtherMenuType.MenuHubOtherMenuType
// NumValues: 0x0006
enum class EMenuHubOtherMenuType : uint8
{
	NewEnumerator3                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator4                           = 4,
	MenuHubOtherMenuType_MAX                 = 5,
};

}

