#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PhotographyFunctionLibrary

#include "Basic.hpp"


namespace SDK::Params
{

// Function PhotographyFunctionLibrary.PhotographyFunctionLibrary_C.Open Photo Camera Screen Ex
// 0x0030 (0x0030 - 0x0000)
struct PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex final 
{
public:
	class APlayerController*                      OwningPlayer;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 WidgetClass;                                       // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_Create_ReturnValue;                       // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class US6UI_StateUserWidget*                  K2Node_DynamicCast_AsS6UI_State_User_Widget;       // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex) == 0x000008, "Wrong alignment on PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex");
static_assert(sizeof(PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex) == 0x000030, "Wrong size on PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex");
static_assert(offsetof(PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex, OwningPlayer) == 0x000000, "Member 'PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex::OwningPlayer' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex, WidgetClass) == 0x000008, "Member 'PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex::WidgetClass' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex, __WorldContext) == 0x000010, "Member 'PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex::__WorldContext' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex, CallFunc_Create_ReturnValue) == 0x000018, "Member 'PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex, K2Node_DynamicCast_AsS6UI_State_User_Widget) == 0x000020, "Member 'PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex::K2Node_DynamicCast_AsS6UI_State_User_Widget' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'PhotographyFunctionLibrary_C_Open_Photo_Camera_Screen_Ex::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function PhotographyFunctionLibrary.PhotographyFunctionLibrary_C.OpenPhotoCameraScreen
// 0x0060 (0x0060 - 0x0000)
struct PhotographyFunctionLibrary_C_OpenPhotoCameraScreen final 
{
public:
	class APlayerController*                      OwningPlayer;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsUser_Widget;             // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsConsole_ReturnValue;                    // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46DE[0x6];                                     // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Create_ReturnValue;                       // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class US6UI_StateUserWidget*                  K2Node_DynamicCast_AsS6UI_State_User_Widget;       // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDesktop_ReturnValue;                    // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46DF[0x6];                                     // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_ClassDynamicCast_AsUser_Widget_1;           // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46E0[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Create_ReturnValue_1;                     // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class US6UI_StateUserWidget*                  K2Node_DynamicCast_AsS6UI_State_User_Widget_1;     // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen) == 0x000008, "Wrong alignment on PhotographyFunctionLibrary_C_OpenPhotoCameraScreen");
static_assert(sizeof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen) == 0x000060, "Wrong size on PhotographyFunctionLibrary_C_OpenPhotoCameraScreen");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, OwningPlayer) == 0x000000, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::OwningPlayer' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, __WorldContext) == 0x000008, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::__WorldContext' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, K2Node_ClassDynamicCast_AsUser_Widget) == 0x000010, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::K2Node_ClassDynamicCast_AsUser_Widget' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, K2Node_ClassDynamicCast_bSuccess) == 0x000018, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, CallFunc_IsConsole_ReturnValue) == 0x000019, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::CallFunc_IsConsole_ReturnValue' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, CallFunc_Create_ReturnValue) == 0x000020, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, K2Node_DynamicCast_AsS6UI_State_User_Widget) == 0x000028, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::K2Node_DynamicCast_AsS6UI_State_User_Widget' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, CallFunc_IsDesktop_ReturnValue) == 0x000031, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::CallFunc_IsDesktop_ReturnValue' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, K2Node_ClassDynamicCast_AsUser_Widget_1) == 0x000038, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::K2Node_ClassDynamicCast_AsUser_Widget_1' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, K2Node_ClassDynamicCast_bSuccess_1) == 0x000040, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, CallFunc_Create_ReturnValue_1) == 0x000048, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, K2Node_DynamicCast_AsS6UI_State_User_Widget_1) == 0x000050, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::K2Node_DynamicCast_AsS6UI_State_User_Widget_1' has a wrong offset!");
static_assert(offsetof(PhotographyFunctionLibrary_C_OpenPhotoCameraScreen, K2Node_DynamicCast_bSuccess_1) == 0x000058, "Member 'PhotographyFunctionLibrary_C_OpenPhotoCameraScreen::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

}

