#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S6OnlineHotfixManager

#include "Basic.hpp"

#include "Hotfix_classes.hpp"


namespace SDK
{

// Class S6OnlineHotfixManager.S6OnlineHotfixManager
// 0x0010 (0x0248 - 0x0238)
class US6OnlineHotfixManager final  : public UOnlineHotfixManager
{
public:
	uint8                                         Pad_1E49[0x10];                                    // 0x0238(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S6OnlineHotfixManager">();
	}
	static class US6OnlineHotfixManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<US6OnlineHotfixManager>();
	}
};
static_assert(alignof(US6OnlineHotfixManager) == 0x000008, "Wrong alignment on US6OnlineHotfixManager");
static_assert(sizeof(US6OnlineHotfixManager) == 0x000248, "Wrong size on US6OnlineHotfixManager");

}

