#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CreditsScreen_PF

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ValeriaUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CreditsScreen_PF.WBP_CreditsScreen_PF_C
// 0x0048 (0x0570 - 0x0528)
class UWBP_CreditsScreen_PF_C final  : public UVALUI_ModalWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0528(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Background;                                        // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVALUI_RichTextBlock_Styled*            CreditsTextBlock;                                  // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVALUI_ScrollBox_Styled*                ScrollBox;                                         // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CommonUIButtonPrompt_C*            WBP_CommonUIButtonPrompt;                          // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	double                                        ScrollOffset;                                      // 0x0550(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CreditScrollSpeed;                                 // 0x0558(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CreditsFileName;                                   // 0x0560(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	bool BP_OnHandleBackAction(class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class US6UI_UIManagerWidgetBase* CallFunc_GetUIManagerWidget_ReturnValue);
	void Construct();
	void Destruct();
	void ExecuteUbergraph_WBP_CreditsScreen_PF(int32 EntryPoint, int32 CallFunc_AkEventGlobal_ReturnValue, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, const class FString& CallFunc_GetProjectContentDirectory_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, class FText CallFunc_LoadFileToText_OutputText, int32 CallFunc_AkEventGlobal_ReturnValue_1, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast, float CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CreditsScreen_PF_C">();
	}
	static class UWBP_CreditsScreen_PF_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CreditsScreen_PF_C>();
	}
};
static_assert(alignof(UWBP_CreditsScreen_PF_C) == 0x000008, "Wrong alignment on UWBP_CreditsScreen_PF_C");
static_assert(sizeof(UWBP_CreditsScreen_PF_C) == 0x000570, "Wrong size on UWBP_CreditsScreen_PF_C");
static_assert(offsetof(UWBP_CreditsScreen_PF_C, UberGraphFrame) == 0x000528, "Member 'UWBP_CreditsScreen_PF_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsScreen_PF_C, Background) == 0x000530, "Member 'UWBP_CreditsScreen_PF_C::Background' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsScreen_PF_C, CreditsTextBlock) == 0x000538, "Member 'UWBP_CreditsScreen_PF_C::CreditsTextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsScreen_PF_C, ScrollBox) == 0x000540, "Member 'UWBP_CreditsScreen_PF_C::ScrollBox' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsScreen_PF_C, WBP_CommonUIButtonPrompt) == 0x000548, "Member 'UWBP_CreditsScreen_PF_C::WBP_CommonUIButtonPrompt' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsScreen_PF_C, ScrollOffset) == 0x000550, "Member 'UWBP_CreditsScreen_PF_C::ScrollOffset' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsScreen_PF_C, CreditScrollSpeed) == 0x000558, "Member 'UWBP_CreditsScreen_PF_C::CreditScrollSpeed' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsScreen_PF_C, CreditsFileName) == 0x000560, "Member 'UWBP_CreditsScreen_PF_C::CreditsFileName' has a wrong offset!");

}

