#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SearchBarButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SearchBarButton.WBP_SearchBarButton_C
// 0x0058 (0x02D0 - 0x0278)
class UWBP_SearchBarButton_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       ExpandSearch;                                      // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UVALUI_Button_Styled*                   Button_CancelSearch;                               // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVALUI_Button_Styled*                   Button_Search;                                     // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonActionWidget*                    CommonActionWidget_RootButton;                     // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVALUI_EditableText_Styled*             EText_SearchBarText;                               // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        RootSwitcher;                                      // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_SearchBar;                                 // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnTextChanged;                                     // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UInputAction*                           In_Input_Action;                                   // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__WBP_SearchBarButton_Button_CancelSearch_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WBP_SearchBarButton_Button_CancelSearch_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_SearchBarButton_Button_Search_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WBP_SearchBarButton_Button_Search_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_SearchBarButton_VALUI_EditableText_Styled_50_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature(class FText& Text);
	void Construct();
	void ExecuteUbergraph_WBP_SearchBarButton(int32 EntryPoint, class FText K2Node_ComponentBoundEvent_Text, int32 CallFunc_AkEventGlobal_ReturnValue);
	void GetSearchText(class FText* Text, class FText CallFunc_GetText_ReturnValue);
	void Handle_Cancel_Search(TDelegate<void()> K2Node_CreateDelegate_OutputDelegate, int32 CallFunc_AkEventGlobal_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimationReverse_ReturnValue);
	void Handle_Start_Search(int32 CallFunc_AkEventGlobal_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue);
	void On_Reverse_Animation_End();
	void OnTextChanged__DelegateSignature(class FText Text);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SearchBarButton_C">();
	}
	static class UWBP_SearchBarButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SearchBarButton_C>();
	}
};
static_assert(alignof(UWBP_SearchBarButton_C) == 0x000008, "Wrong alignment on UWBP_SearchBarButton_C");
static_assert(sizeof(UWBP_SearchBarButton_C) == 0x0002D0, "Wrong size on UWBP_SearchBarButton_C");
static_assert(offsetof(UWBP_SearchBarButton_C, UberGraphFrame) == 0x000278, "Member 'UWBP_SearchBarButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, ExpandSearch) == 0x000280, "Member 'UWBP_SearchBarButton_C::ExpandSearch' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, Button_CancelSearch) == 0x000288, "Member 'UWBP_SearchBarButton_C::Button_CancelSearch' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, Button_Search) == 0x000290, "Member 'UWBP_SearchBarButton_C::Button_Search' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, CommonActionWidget_RootButton) == 0x000298, "Member 'UWBP_SearchBarButton_C::CommonActionWidget_RootButton' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, EText_SearchBarText) == 0x0002A0, "Member 'UWBP_SearchBarButton_C::EText_SearchBarText' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, RootSwitcher) == 0x0002A8, "Member 'UWBP_SearchBarButton_C::RootSwitcher' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, SizeBox_SearchBar) == 0x0002B0, "Member 'UWBP_SearchBarButton_C::SizeBox_SearchBar' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, OnTextChanged) == 0x0002B8, "Member 'UWBP_SearchBarButton_C::OnTextChanged' has a wrong offset!");
static_assert(offsetof(UWBP_SearchBarButton_C, In_Input_Action) == 0x0002C8, "Member 'UWBP_SearchBarButton_C::In_Input_Action' has a wrong offset!");

}

