#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Button_ManageFriends

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonWidgetInputExtended_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Button_ManageFriends.WBP_Button_ManageFriends_C
// 0x0080 (0x03D8 - 0x0358)
class UWBP_Button_ManageFriends_C final  : public UCommonUserWidgetInputExtended
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_Button_Icon_CM_C*                  WBP_Button_Icon_CM;                                // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_FocusTip_CM_C*                     WBP_FocusTip_CM;                                   // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       UserId;                                            // 0x0370(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 CharacterName;                                     // 0x03A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnMarkFocusUI;                                     // 0x03B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bIsShowFocusTip;                                   // 0x03C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A79[0x7];                                     // 0x03C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnButtonClicked;                                   // 0x03C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__WBP_Button_ManageFriends_WBP_Button_Icon_CM_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_PlayerCharacterRow_Button_Friend_CM_WBP_Button_Icon_CM_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_PlayerCharacterRow_Button_Friend_CM_WBP_Button_Icon_CM_K2Node_ComponentBoundEvent_1_OnFocused__DelegateSignature();
	void BndEvt__WBP_PlayerCharacterRow_Button_Friend_CM_WBP_Button_Icon_CM_K2Node_ComponentBoundEvent_2_OnUnfocused__DelegateSignature();
	void Construct();
	void Destruct();
	void ExecuteUbergraph_WBP_Button_ManageFriends(int32 EntryPoint, int32 CallFunc_AkEventGlobal_ReturnValue, class UCommonButtonBase* K2Node_ComponentBoundEvent_Button_1, const struct FFocusEvent& K2Node_Event_InFocusEvent, class UCommonButtonBase* K2Node_ComponentBoundEvent_Button);
	void HandleOnFocused();
	void OnButtonClicked__DelegateSignature();
	void OnFocusLost(const struct FFocusEvent& InFocusEvent);
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent, const struct FF_CommonUIButtonPrompt& K2Node_MakeStruct_F_CommonUIButtonPrompt, const struct FF_CommonUIButtonPrompt& K2Node_MakeStruct_F_CommonUIButtonPrompt_1, const struct FEventReply& CallFunc_Handled_ReturnValue, TArray<struct FF_CommonUIButtonPrompt>& K2Node_MakeArray_Array);
	void OnMarkFocusUI__DelegateSignature(class UWidget* Widget, TArray<struct FF_CommonUIButtonPrompt>& Uiprompt);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Button_ManageFriends_C">();
	}
	static class UWBP_Button_ManageFriends_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Button_ManageFriends_C>();
	}
};
static_assert(alignof(UWBP_Button_ManageFriends_C) == 0x000008, "Wrong alignment on UWBP_Button_ManageFriends_C");
static_assert(sizeof(UWBP_Button_ManageFriends_C) == 0x0003D8, "Wrong size on UWBP_Button_ManageFriends_C");
static_assert(offsetof(UWBP_Button_ManageFriends_C, UberGraphFrame) == 0x000358, "Member 'UWBP_Button_ManageFriends_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Button_ManageFriends_C, WBP_Button_Icon_CM) == 0x000360, "Member 'UWBP_Button_ManageFriends_C::WBP_Button_Icon_CM' has a wrong offset!");
static_assert(offsetof(UWBP_Button_ManageFriends_C, WBP_FocusTip_CM) == 0x000368, "Member 'UWBP_Button_ManageFriends_C::WBP_FocusTip_CM' has a wrong offset!");
static_assert(offsetof(UWBP_Button_ManageFriends_C, UserId) == 0x000370, "Member 'UWBP_Button_ManageFriends_C::UserId' has a wrong offset!");
static_assert(offsetof(UWBP_Button_ManageFriends_C, CharacterName) == 0x0003A0, "Member 'UWBP_Button_ManageFriends_C::CharacterName' has a wrong offset!");
static_assert(offsetof(UWBP_Button_ManageFriends_C, OnMarkFocusUI) == 0x0003B0, "Member 'UWBP_Button_ManageFriends_C::OnMarkFocusUI' has a wrong offset!");
static_assert(offsetof(UWBP_Button_ManageFriends_C, bIsShowFocusTip) == 0x0003C0, "Member 'UWBP_Button_ManageFriends_C::bIsShowFocusTip' has a wrong offset!");
static_assert(offsetof(UWBP_Button_ManageFriends_C, OnButtonClicked) == 0x0003C8, "Member 'UWBP_Button_ManageFriends_C::OnButtonClicked' has a wrong offset!");

}

