#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GamepadSettings_CM

#include "Basic.hpp"

#include "E_CloseKeyRebindMenuType_structs.hpp"
#include "EnhancedInput_structs.hpp"
#include "CommonInput_structs.hpp"


namespace SDK::Params
{

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.ActiveFocusAndPrompt
// 0x0008 (0x0008 - 0x0000)
struct WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt final 
{
public:
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt) == 0x000004, "Wrong alignment on WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt");
static_assert(sizeof(WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt) == 0x000008, "Wrong size on WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt, CallFunc_GetActiveWidgetIndex_ReturnValue) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt::CallFunc_GetActiveWidgetIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt, K2Node_SwitchInteger_CmpSuccess) == 0x000004, "Member 'WBP_GamepadSettings_CM_C_ActiveFocusAndPrompt::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_GamepadSettings_CM_Checkbox_CameraAssist_K2Node_ComponentBoundEvent_7_OnCheckedStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_CameraAssist_K2Node_ComponentBoundEvent_7_OnCheckedStateChanged__DelegateSignature final 
{
public:
	bool                                          Checked;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_CameraAssist_K2Node_ComponentBoundEvent_7_OnCheckedStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_CameraAssist_K2Node_ComponentBoundEvent_7_OnCheckedStateChanged__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_CameraAssist_K2Node_ComponentBoundEvent_7_OnCheckedStateChanged__DelegateSignature) == 0x000001, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_CameraAssist_K2Node_ComponentBoundEvent_7_OnCheckedStateChanged__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_CameraAssist_K2Node_ComponentBoundEvent_7_OnCheckedStateChanged__DelegateSignature, Checked) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_CameraAssist_K2Node_ComponentBoundEvent_7_OnCheckedStateChanged__DelegateSignature::Checked' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_GamepadSettings_CM_Checkbox_ThumbstickScheme_K2Node_ComponentBoundEvent_8_OnCheckedStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_ThumbstickScheme_K2Node_ComponentBoundEvent_8_OnCheckedStateChanged__DelegateSignature final 
{
public:
	bool                                          Checked;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_ThumbstickScheme_K2Node_ComponentBoundEvent_8_OnCheckedStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_ThumbstickScheme_K2Node_ComponentBoundEvent_8_OnCheckedStateChanged__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_ThumbstickScheme_K2Node_ComponentBoundEvent_8_OnCheckedStateChanged__DelegateSignature) == 0x000001, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_ThumbstickScheme_K2Node_ComponentBoundEvent_8_OnCheckedStateChanged__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_ThumbstickScheme_K2Node_ComponentBoundEvent_8_OnCheckedStateChanged__DelegateSignature, Checked) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Checkbox_ThumbstickScheme_K2Node_ComponentBoundEvent_8_OnCheckedStateChanged__DelegateSignature::Checked' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_GamepadSettings_CM_Slider_AimSensitivity_K2Node_ComponentBoundEvent_3_OnSliderValueChanged__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_AimSensitivity_K2Node_ComponentBoundEvent_3_OnSliderValueChanged__DelegateSignature final 
{
public:
	double                                        Value;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_AimSensitivity_K2Node_ComponentBoundEvent_3_OnSliderValueChanged__DelegateSignature) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_AimSensitivity_K2Node_ComponentBoundEvent_3_OnSliderValueChanged__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_AimSensitivity_K2Node_ComponentBoundEvent_3_OnSliderValueChanged__DelegateSignature) == 0x000008, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_AimSensitivity_K2Node_ComponentBoundEvent_3_OnSliderValueChanged__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_AimSensitivity_K2Node_ComponentBoundEvent_3_OnSliderValueChanged__DelegateSignature, Value) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_AimSensitivity_K2Node_ComponentBoundEvent_3_OnSliderValueChanged__DelegateSignature::Value' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_GamepadSettings_CM_Slider_ControllerYSensitivity_K2Node_ComponentBoundEvent_0_OnSliderValueChanged__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_ControllerYSensitivity_K2Node_ComponentBoundEvent_0_OnSliderValueChanged__DelegateSignature final 
{
public:
	double                                        Value;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_ControllerYSensitivity_K2Node_ComponentBoundEvent_0_OnSliderValueChanged__DelegateSignature) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_ControllerYSensitivity_K2Node_ComponentBoundEvent_0_OnSliderValueChanged__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_ControllerYSensitivity_K2Node_ComponentBoundEvent_0_OnSliderValueChanged__DelegateSignature) == 0x000008, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_ControllerYSensitivity_K2Node_ComponentBoundEvent_0_OnSliderValueChanged__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_ControllerYSensitivity_K2Node_ComponentBoundEvent_0_OnSliderValueChanged__DelegateSignature, Value) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_ControllerYSensitivity_K2Node_ComponentBoundEvent_0_OnSliderValueChanged__DelegateSignature::Value' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_GamepadSettings_CM_Slider_RumbleIntensity_K2Node_ComponentBoundEvent_1_OnSliderValueChanged__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_RumbleIntensity_K2Node_ComponentBoundEvent_1_OnSliderValueChanged__DelegateSignature final 
{
public:
	double                                        Value;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_RumbleIntensity_K2Node_ComponentBoundEvent_1_OnSliderValueChanged__DelegateSignature) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_RumbleIntensity_K2Node_ComponentBoundEvent_1_OnSliderValueChanged__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_RumbleIntensity_K2Node_ComponentBoundEvent_1_OnSliderValueChanged__DelegateSignature) == 0x000008, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_RumbleIntensity_K2Node_ComponentBoundEvent_1_OnSliderValueChanged__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_RumbleIntensity_K2Node_ComponentBoundEvent_1_OnSliderValueChanged__DelegateSignature, Value) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_Slider_RumbleIntensity_K2Node_ComponentBoundEvent_1_OnSliderValueChanged__DelegateSignature::Value' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_GamepadSettings_CM_TabSelector_K2Node_ComponentBoundEvent_6_On Tab Selection Changed__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_TabSelector_K2Node_ComponentBoundEvent_6_On_Tab_Selection_Changed__DelegateSignature final 
{
public:
	int32                                         Tab_Selection;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_TabSelector_K2Node_ComponentBoundEvent_6_On_Tab_Selection_Changed__DelegateSignature) == 0x000004, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_TabSelector_K2Node_ComponentBoundEvent_6_On_Tab_Selection_Changed__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_TabSelector_K2Node_ComponentBoundEvent_6_On_Tab_Selection_Changed__DelegateSignature) == 0x000004, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_TabSelector_K2Node_ComponentBoundEvent_6_On_Tab_Selection_Changed__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_TabSelector_K2Node_ComponentBoundEvent_6_On_Tab_Selection_Changed__DelegateSignature, Tab_Selection) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_TabSelector_K2Node_ComponentBoundEvent_6_On_Tab_Selection_Changed__DelegateSignature::Tab_Selection' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature final 
{
public:
	E_CloseKeyRebindMenuType                      ExcuteStatus;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E8D[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                InWidget;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature) == 0x000010, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature, ExcuteStatus) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature::ExcuteStatus' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature, InWidget) == 0x000008, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_GamepadSettings_CM_WBP_KeyRebindingMenu_Gamepad_K2Node_ComponentBoundEvent_10_OnKeyRebindConfirmExit__DelegateSignature::InWidget' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_2_OnCheckedStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_2_OnCheckedStateChanged__DelegateSignature final 
{
public:
	bool                                          Checked;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_2_OnCheckedStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_2_OnCheckedStateChanged__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_2_OnCheckedStateChanged__DelegateSignature) == 0x000001, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_2_OnCheckedStateChanged__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_2_OnCheckedStateChanged__DelegateSignature, Checked) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_2_OnCheckedStateChanged__DelegateSignature::Checked' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_4_OnCheckedStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_4_OnCheckedStateChanged__DelegateSignature final 
{
public:
	bool                                          Checked;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_4_OnCheckedStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_4_OnCheckedStateChanged__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_4_OnCheckedStateChanged__DelegateSignature) == 0x000001, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_4_OnCheckedStateChanged__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_4_OnCheckedStateChanged__DelegateSignature, Checked) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Checkbox_CM_K2Node_ComponentBoundEvent_4_OnCheckedStateChanged__DelegateSignature::Checked' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Slider_CM_K2Node_ComponentBoundEvent_5_OnSliderValueChanged__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Slider_CM_K2Node_ComponentBoundEvent_5_OnSliderValueChanged__DelegateSignature final 
{
public:
	double                                        Value;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Slider_CM_K2Node_ComponentBoundEvent_5_OnSliderValueChanged__DelegateSignature) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Slider_CM_K2Node_ComponentBoundEvent_5_OnSliderValueChanged__DelegateSignature");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Slider_CM_K2Node_ComponentBoundEvent_5_OnSliderValueChanged__DelegateSignature) == 0x000008, "Wrong size on WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Slider_CM_K2Node_ComponentBoundEvent_5_OnSliderValueChanged__DelegateSignature");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Slider_CM_K2Node_ComponentBoundEvent_5_OnSliderValueChanged__DelegateSignature, Value) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BndEvt__WBP_KeyRebindingSettings_CM_WBP_SettingsItem_Slider_CM_K2Node_ComponentBoundEvent_5_OnSliderValueChanged__DelegateSignature::Value' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.CheckandCloseKeyRebindMenu
// 0x0004 (0x0004 - 0x0000)
struct WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu final 
{
public:
	E_CloseKeyRebindMenuType                      ExcuteStatus;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bCloseSuceessed;                                   // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsActivated_ReturnValue;                  // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckandCloseKeyRebindMenu_bCloseSuccessed; // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu) == 0x000001, "Wrong alignment on WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu");
static_assert(sizeof(WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu) == 0x000004, "Wrong size on WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu");
static_assert(offsetof(WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu, ExcuteStatus) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu::ExcuteStatus' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu, bCloseSuceessed) == 0x000001, "Member 'WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu::bCloseSuceessed' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu, CallFunc_IsActivated_ReturnValue) == 0x000002, "Member 'WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu::CallFunc_IsActivated_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu, CallFunc_CheckandCloseKeyRebindMenu_bCloseSuccessed) == 0x000003, "Member 'WBP_GamepadSettings_CM_C_CheckandCloseKeyRebindMenu::CallFunc_CheckandCloseKeyRebindMenu_bCloseSuccessed' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.ExecuteUbergraph_WBP_GamepadSettings_CM
// 0x0330 (0x0330 - 0x0000)
struct WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM final 
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E8E[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable;                                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E8F[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue;       // 0x0018(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime;       // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime;     // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           K2Node_EnhancedInputActionEvent_SourceAction;      // 0x0040(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           Temp_object_Variable;                              // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue;  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E90[0x7];                                     // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable_1;                              // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2;                              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1_0;                            // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2_0;                            // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E91[0x7];                                     // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3;                              // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0090(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           Temp_object_Variable_1;                            // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E92[0x3];                                     // 0x00B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_1;     // 0x00B8(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_1;     // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_1;   // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           K2Node_EnhancedInputActionEvent_SourceAction_1;    // 0x00E0(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue_1;            // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3_0;                            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_0;                              // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_1; // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E93[0x6];                                     // 0x0102(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_Name;                           // 0x0108(0x0018)()
	class FText                                   K2Node_CustomEvent_Description;                    // 0x0120(0x0018)()
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue;   // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0140(0x0010)(ReferenceParm, ContainsInstancedReference)
	bool                                          Temp_bool_Variable_2;                              // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E94[0x7];                                     // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0158(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E95[0x4];                                     // 0x0164(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_SettingsItem_Parent_DoNotEdit_C*   K2Node_DynamicCast_AsWBP_Settings_Item_Parent_Do_Not_Edit; // 0x0168(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E96[0x7];                                     // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue_1; // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_4;                              // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_5;                              // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue_2; // 0x0190(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           Temp_object_Variable_2;                            // 0x0198(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_2;     // 0x01A0(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_2;     // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_2;   // 0x01C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           K2Node_EnhancedInputActionEvent_SourceAction_2;    // 0x01C8(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_Checked_3;              // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E97[0x7];                                     // 0x01D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable_5_0;                            // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_4_0;                            // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_2; // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_Checked_2;              // 0x01E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E98[0x6];                                     // 0x01EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_ComponentBoundEvent_Value_3;                // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_ComponentBoundEvent_Value_2;                // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue_3; // 0x0200(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue_4; // 0x0210(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_ComponentBoundEvent_Value_1;                // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue_5; // 0x0220(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue_6; // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_Checked_1;              // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E99[0x7];                                     // 0x0231(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_ComponentBoundEvent_Value;                  // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9A[0x7];                                     // 0x0241(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable_6;                              // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_7;                              // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           Temp_object_Variable_3;                            // 0x0258(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Tab_Selection;          // 0x0260(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9B[0x4];                                     // 0x0264(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_3;     // 0x0268(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_3;     // 0x0288(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_3;   // 0x028C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           K2Node_EnhancedInputActionEvent_SourceAction_3;    // 0x0290(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_7_0;                            // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_6_0;                            // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_3; // 0x02A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9C[0x3];                                     // 0x02A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x02AC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              K2Node_CustomEvent_bNewInputType;                  // 0x02BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x02BD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_Checked;                // 0x02BE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9D[0x1];                                     // 0x02BF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue_7; // 0x02C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FText Name, class FText Description)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x02C8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckandCloseKeyRebindMenu_bCloseSuceessed; // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckandCloseKeyRebindMenu_bCloseSuceessed_1; // 0x02D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_CloseKeyRebindMenuType                      K2Node_ComponentBoundEvent_ExcuteStatus;           // 0x02DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9E[0x5];                                     // 0x02DB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_ComponentBoundEvent_InWidget;               // 0x02E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_2;    // 0x02E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9F[0x2];                                     // 0x02EA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x02EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA0[0x3];                                     // 0x02F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x02F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue_1;    // 0x02F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x0300(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA1[0x7];                                     // 0x0311(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0318(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetControllerYAxisSensitivity_sensitivity_ImplicitCast; // 0x0320(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetControllerAimSensitivityMultiplier_SensitivityMultiplier_ImplicitCast; // 0x0324(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetControllerForceFeedbackScale_Scale_ImplicitCast; // 0x0328(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetControllerXAxisSensitivity_sensitivity_ImplicitCast; // 0x032C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM");
static_assert(sizeof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM) == 0x000330, "Wrong size on WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, EntryPoint) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable) == 0x000008, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_bool_Variable) == 0x000010, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_ActionValue) == 0x000018, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_ElapsedTime) == 0x000038, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_TriggeredTime) == 0x00003C, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_SourceAction) == 0x000040, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_SourceAction' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_object_Variable) == 0x000048, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Conv_InputActionValueToBool_ReturnValue) == 0x000050, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Conv_InputActionValueToBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_1) == 0x000058, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_2) == 0x000060, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_1_0) == 0x000068, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_1_0' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_2_0) == 0x000070, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_2_0' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_bool_Variable_1) == 0x000078, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000080, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_3) == 0x000088, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_CreateDelegate_OutputDelegate) == 0x000090, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetActiveWidget_ReturnValue) == 0x0000A0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_object_Variable_1) == 0x0000A8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_int_Array_Index_Variable) == 0x0000B0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0000B4, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_ActionValue_1) == 0x0000B8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_ActionValue_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_ElapsedTime_1) == 0x0000D8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_ElapsedTime_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_TriggeredTime_1) == 0x0000DC, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_TriggeredTime_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_SourceAction_1) == 0x0000E0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_SourceAction_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetActiveWidget_ReturnValue_1) == 0x0000E8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetActiveWidget_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_3_0) == 0x0000F0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_3_0' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_0) == 0x0000F8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_0' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Conv_InputActionValueToBool_ReturnValue_1) == 0x000100, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Conv_InputActionValueToBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x000101, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_CustomEvent_Name) == 0x000108, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_CustomEvent_Name' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_CustomEvent_Description) == 0x000120, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_CustomEvent_Description' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetValeriaGameUserSettings_ReturnValue) == 0x000138, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetValeriaGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetAllChildren_ReturnValue) == 0x000140, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_bool_Variable_2) == 0x000150, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Array_Get_Item) == 0x000158, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Array_Length_ReturnValue) == 0x000160, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_DynamicCast_AsWBP_Settings_Item_Parent_Do_Not_Edit) == 0x000168, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_DynamicCast_AsWBP_Settings_Item_Parent_Do_Not_Edit' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_DynamicCast_bSuccess) == 0x000170, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetValeriaGameUserSettings_ReturnValue_1) == 0x000178, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetValeriaGameUserSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_4) == 0x000180, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_5) == 0x000188, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetValeriaGameUserSettings_ReturnValue_2) == 0x000190, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetValeriaGameUserSettings_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_object_Variable_2) == 0x000198, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_ActionValue_2) == 0x0001A0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_ActionValue_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_ElapsedTime_2) == 0x0001C0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_ElapsedTime_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_TriggeredTime_2) == 0x0001C4, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_TriggeredTime_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_SourceAction_2) == 0x0001C8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_SourceAction_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Checked_3) == 0x0001D0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Checked_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_5_0) == 0x0001D8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_5_0' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_4_0) == 0x0001E0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_4_0' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Conv_InputActionValueToBool_ReturnValue_2) == 0x0001E8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Conv_InputActionValueToBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Checked_2) == 0x0001E9, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Checked_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Value_3) == 0x0001F0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Value_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Value_2) == 0x0001F8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Value_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetValeriaGameUserSettings_ReturnValue_3) == 0x000200, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetValeriaGameUserSettings_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000208, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetValeriaGameUserSettings_ReturnValue_4) == 0x000210, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetValeriaGameUserSettings_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Value_1) == 0x000218, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Value_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetValeriaGameUserSettings_ReturnValue_5) == 0x000220, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetValeriaGameUserSettings_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetValeriaGameUserSettings_ReturnValue_6) == 0x000228, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetValeriaGameUserSettings_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Checked_1) == 0x000230, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Checked_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Value) == 0x000238, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Value' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_bool_Variable_3) == 0x000240, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_6) == 0x000248, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_6' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_7) == 0x000250, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_7' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_object_Variable_3) == 0x000258, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Tab_Selection) == 0x000260, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Tab_Selection' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_ActionValue_3) == 0x000268, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_ActionValue_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_ElapsedTime_3) == 0x000288, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_ElapsedTime_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_TriggeredTime_3) == 0x00028C, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_TriggeredTime_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_EnhancedInputActionEvent_SourceAction_3) == 0x000290, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_EnhancedInputActionEvent_SourceAction_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_7_0) == 0x000298, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_7_0' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_real_Variable_6_0) == 0x0002A0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_real_Variable_6_0' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Conv_InputActionValueToBool_ReturnValue_3) == 0x0002A8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Conv_InputActionValueToBool_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_CreateDelegate_OutputDelegate_1) == 0x0002AC, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_CustomEvent_bNewInputType) == 0x0002BC, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_CustomEvent_bNewInputType' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_SwitchEnum_CmpSuccess) == 0x0002BD, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_Checked) == 0x0002BE, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_Checked' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetValeriaGameUserSettings_ReturnValue_7) == 0x0002C0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetValeriaGameUserSettings_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_CreateDelegate_OutputDelegate_2) == 0x0002C8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_CheckandCloseKeyRebindMenu_bCloseSuceessed) == 0x0002D8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_CheckandCloseKeyRebindMenu_bCloseSuceessed' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_CheckandCloseKeyRebindMenu_bCloseSuceessed_1) == 0x0002D9, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_CheckandCloseKeyRebindMenu_bCloseSuceessed_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_ExcuteStatus) == 0x0002DA, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_ExcuteStatus' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_ComponentBoundEvent_InWidget) == 0x0002E0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_ComponentBoundEvent_InWidget' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_SwitchEnum_CmpSuccess_1) == 0x0002E8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_EqualEqual_ObjectObject_ReturnValue_2) == 0x0002E9, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_EqualEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, Temp_int_Loop_Counter_Variable) == 0x0002EC, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Less_IntInt_ReturnValue) == 0x0002F0, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Add_IntInt_ReturnValue) == 0x0002F4, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetLocalPlayerSubsystem_ReturnValue_1) == 0x0002F8, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetLocalPlayerSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, K2Node_CreateDelegate_OutputDelegate_3) == 0x000300, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_GetCurrentInputType_ReturnValue) == 0x000310, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000318, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_SetControllerYAxisSensitivity_sensitivity_ImplicitCast) == 0x000320, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_SetControllerYAxisSensitivity_sensitivity_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_SetControllerAimSensitivityMultiplier_SensitivityMultiplier_ImplicitCast) == 0x000324, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_SetControllerAimSensitivityMultiplier_SensitivityMultiplier_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_SetControllerForceFeedbackScale_Scale_ImplicitCast) == 0x000328, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_SetControllerForceFeedbackScale_Scale_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM, CallFunc_SetControllerXAxisSensitivity_sensitivity_ImplicitCast) == 0x00032C, "Member 'WBP_GamepadSettings_CM_C_ExecuteUbergraph_WBP_GamepadSettings_CM::CallFunc_SetControllerXAxisSensitivity_sensitivity_ImplicitCast' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.HandleSettingsItemHovered
// 0x0030 (0x0030 - 0x0000)
struct WBP_GamepadSettings_CM_C_HandleSettingsItemHovered final 
{
public:
	class FText                                   Param_Name;                                        // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   Description;                                       // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_HandleSettingsItemHovered) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_HandleSettingsItemHovered");
static_assert(sizeof(WBP_GamepadSettings_CM_C_HandleSettingsItemHovered) == 0x000030, "Wrong size on WBP_GamepadSettings_CM_C_HandleSettingsItemHovered");
static_assert(offsetof(WBP_GamepadSettings_CM_C_HandleSettingsItemHovered, Param_Name) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_HandleSettingsItemHovered::Param_Name' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_HandleSettingsItemHovered, Description) == 0x000018, "Member 'WBP_GamepadSettings_CM_C_HandleSettingsItemHovered::Description' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2
// 0x0030 (0x0030 - 0x0000)
struct WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2 final 
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2");
static_assert(sizeof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2) == 0x000030, "Wrong size on WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2, ActionValue) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2, ElapsedTime) == 0x000020, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2, TriggeredTime) == 0x000024, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2, SourceAction) == 0x000028, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Down_K2Node_EnhancedInputActionEvent_2::SourceAction' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3
// 0x0030 (0x0030 - 0x0000)
struct WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3 final 
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3");
static_assert(sizeof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3) == 0x000030, "Wrong size on WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3, ActionValue) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3, ElapsedTime) == 0x000020, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3, TriggeredTime) == 0x000024, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3, SourceAction) == 0x000028, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_ScrollBar_Up_K2Node_EnhancedInputActionEvent_3::SourceAction' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0
// 0x0030 (0x0030 - 0x0000)
struct WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0 final 
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0");
static_assert(sizeof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0) == 0x000030, "Wrong size on WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0, ActionValue) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0, ElapsedTime) == 0x000020, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0, TriggeredTime) == 0x000024, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0, SourceAction) == 0x000028, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_L_K2Node_EnhancedInputActionEvent_0::SourceAction' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1
// 0x0030 (0x0030 - 0x0000)
struct WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1 final 
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1");
static_assert(sizeof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1) == 0x000030, "Wrong size on WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1, ActionValue) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1, ElapsedTime) == 0x000020, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1, TriggeredTime) == 0x000024, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1, SourceAction) == 0x000028, "Member 'WBP_GamepadSettings_CM_C_InpActEvt_IA_UI_SecondaryTab_Switch_R_K2Node_EnhancedInputActionEvent_1::SourceAction' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.OnInputMethodChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_GamepadSettings_CM_C_OnInputMethodChanged final 
{
public:
	ECommonInputType                              bNewInputType;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_OnInputMethodChanged) == 0x000001, "Wrong alignment on WBP_GamepadSettings_CM_C_OnInputMethodChanged");
static_assert(sizeof(WBP_GamepadSettings_CM_C_OnInputMethodChanged) == 0x000001, "Wrong size on WBP_GamepadSettings_CM_C_OnInputMethodChanged");
static_assert(offsetof(WBP_GamepadSettings_CM_C_OnInputMethodChanged, bNewInputType) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_OnInputMethodChanged::bNewInputType' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.SetScrollUp
// 0x0068 (0x0068 - 0x0000)
struct WBP_GamepadSettings_CM_C_SetScrollUp final 
{
public:
	bool                                          bIsMoveUp;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA2[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable;                                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1;                              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA3[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_Select_Default;                             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScrollOffsetOfEnd_ReturnValue;         // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA4[0x4];                                     // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScrollOffset_ReturnValue;              // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA5[0x4];                                     // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_Max_ImplicitCast;                  // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_B_ImplicitCast;          // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast; // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_SetScrollUp) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_SetScrollUp");
static_assert(sizeof(WBP_GamepadSettings_CM_C_SetScrollUp) == 0x000068, "Wrong size on WBP_GamepadSettings_CM_C_SetScrollUp");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, bIsMoveUp) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::bIsMoveUp' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, Temp_real_Variable) == 0x000008, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, Temp_real_Variable_1) == 0x000010, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::Temp_real_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, Temp_bool_Variable) == 0x000018, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, K2Node_Select_Default) == 0x000020, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, CallFunc_GetScrollOffsetOfEnd_ReturnValue) == 0x000028, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::CallFunc_GetScrollOffsetOfEnd_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000030, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, CallFunc_GetScrollOffset_ReturnValue) == 0x000038, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::CallFunc_GetScrollOffset_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000040, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, CallFunc_FClamp_ReturnValue) == 0x000048, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, CallFunc_FClamp_Max_ImplicitCast) == 0x000050, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::CallFunc_FClamp_Max_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, CallFunc_Add_DoubleDouble_B_ImplicitCast) == 0x000058, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::CallFunc_Add_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SetScrollUp, CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast) == 0x000060, "Member 'WBP_GamepadSettings_CM_C_SetScrollUp::CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.SynchronizeInputSettings
// 0x0048 (0x0048 - 0x0000)
struct WBP_GamepadSettings_CM_C_SynchronizeInputSettings final 
{
public:
	class UValeriaGameUserSettings*               CallFunc_GetValeriaGameUserSettings_ReturnValue;   // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetEnableCameraAssist_ReturnValue;        // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA6[0x7];                                     // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast;       // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast_1;     // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SetSliderValue_SliderValue_ImplicitCast;  // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_A_ImplicitCast;               // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_SynchronizeInputSettings");
static_assert(sizeof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings) == 0x000048, "Wrong size on WBP_GamepadSettings_CM_C_SynchronizeInputSettings");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_GetValeriaGameUserSettings_ReturnValue) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_GetValeriaGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_GetEnableCameraAssist_ReturnValue) == 0x000008, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_GetEnableCameraAssist_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_SelectFloat_ReturnValue) == 0x000010, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000018, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x000020, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_Divide_DoubleDouble_A_ImplicitCast) == 0x000028, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_Divide_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_Divide_DoubleDouble_A_ImplicitCast_1) == 0x000030, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_Divide_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_SetSliderValue_SliderValue_ImplicitCast) == 0x000038, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_SetSliderValue_SliderValue_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_SynchronizeInputSettings, CallFunc_SelectFloat_A_ImplicitCast) == 0x000040, "Member 'WBP_GamepadSettings_CM_C_SynchronizeInputSettings::CallFunc_SelectFloat_A_ImplicitCast' has a wrong offset!");

// Function WBP_GamepadSettings_CM.WBP_GamepadSettings_CM_C.BP_GetDesiredFocusTarget
// 0x0028 (0x0028 - 0x0000)
struct WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget final 
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA7[0x4];                                     // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetDesiredFocusTarget_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA8[0x4];                                     // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_Select_Default;                             // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget) == 0x000028, "Wrong size on WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget, Temp_int_Variable) == 0x000008, "Member 'WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget, CallFunc_GetDesiredFocusTarget_ReturnValue) == 0x000010, "Member 'WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget::CallFunc_GetDesiredFocusTarget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget, CallFunc_GetActiveWidgetIndex_ReturnValue) == 0x000018, "Member 'WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget::CallFunc_GetActiveWidgetIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget, K2Node_Select_Default) == 0x000020, "Member 'WBP_GamepadSettings_CM_C_BP_GetDesiredFocusTarget::K2Node_Select_Default' has a wrong offset!");

}

