#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlatformPlayerNameToolTip

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PlatformPlayerNameToolTip.WBP_PlatformPlayerNameToolTip_C
// 0x0048 (0x02C0 - 0x0278)
class UWBP_PlatformPlayerNameToolTip_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVALUI_TextBlock_Styled*                Text_OnlineID;                                     // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PlatformPlayerName_C*              WBP_PlatformPlayerName;                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       OwnerNetId;                                        // 0x0290(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PlatformPlayerNameToolTip(int32 EntryPoint, class UPresenceManager* CallFunc_GetLocalPlayerSubsystem_ReturnValue, const struct FPresence& CallFunc_GetPresenceForUserId_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue_1, bool CallFunc_IsEmpty_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1);
	void Refresh_Platform_Data();
	void UpdatePlatformData(const struct FUniqueNetIdRepl& NetId, bool CallFunc_IsValid_ReturnValue);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PlatformPlayerNameToolTip_C">();
	}
	static class UWBP_PlatformPlayerNameToolTip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlatformPlayerNameToolTip_C>();
	}
};
static_assert(alignof(UWBP_PlatformPlayerNameToolTip_C) == 0x000008, "Wrong alignment on UWBP_PlatformPlayerNameToolTip_C");
static_assert(sizeof(UWBP_PlatformPlayerNameToolTip_C) == 0x0002C0, "Wrong size on UWBP_PlatformPlayerNameToolTip_C");
static_assert(offsetof(UWBP_PlatformPlayerNameToolTip_C, UberGraphFrame) == 0x000278, "Member 'UWBP_PlatformPlayerNameToolTip_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PlatformPlayerNameToolTip_C, Text_OnlineID) == 0x000280, "Member 'UWBP_PlatformPlayerNameToolTip_C::Text_OnlineID' has a wrong offset!");
static_assert(offsetof(UWBP_PlatformPlayerNameToolTip_C, WBP_PlatformPlayerName) == 0x000288, "Member 'UWBP_PlatformPlayerNameToolTip_C::WBP_PlatformPlayerName' has a wrong offset!");
static_assert(offsetof(UWBP_PlatformPlayerNameToolTip_C, OwnerNetId) == 0x000290, "Member 'UWBP_PlatformPlayerNameToolTip_C::OwnerNetId' has a wrong offset!");

}

