#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EditPlotModeIndicatorOverlay

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EditPlotModeIndicatorOverlay.WBP_EditPlotModeIndicatorOverlay_C
// 0x0008 (0x0280 - 0x0278)
class UWBP_EditPlotModeIndicatorOverlay_C final  : public UUserWidget
{
public:
	class UVALUI_Border_Styled*                   Border;                                            // 0x0278(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_EditPlotModeIndicatorOverlay_C">();
	}
	static class UWBP_EditPlotModeIndicatorOverlay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EditPlotModeIndicatorOverlay_C>();
	}
};
static_assert(alignof(UWBP_EditPlotModeIndicatorOverlay_C) == 0x000008, "Wrong alignment on UWBP_EditPlotModeIndicatorOverlay_C");
static_assert(sizeof(UWBP_EditPlotModeIndicatorOverlay_C) == 0x000280, "Wrong size on UWBP_EditPlotModeIndicatorOverlay_C");
static_assert(offsetof(UWBP_EditPlotModeIndicatorOverlay_C, Border) == 0x000278, "Member 'UWBP_EditPlotModeIndicatorOverlay_C::Border' has a wrong offset!");

}

