#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Template_ProgressTracker_CM

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Template_ProgressTracker_CM.WBP_Template_ProgressTracker_CM_C
// 0x0040 (0x02B8 - 0x0278)
class UWBP_Template_ProgressTracker_CM_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         HorizontalBox_TrackingImages;                      // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVALUI_ProgressBar_Styled*              VALUI_ProgressBar_Styled_67;                       // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         MaxPages;                                          // 0x0290(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46D6[0x4];                                     // 0x0294(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_Template_ProgressTrackerImage_C*> PageWidgets;                                       // 0x0298(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	int32                                         ActivePage;                                        // 0x02A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46D7[0x4];                                     // 0x02AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        TrackerSpacing;                                    // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Template_ProgressTracker_CM(int32 EntryPoint, const struct FMargin& K2Node_MakeStruct_Margin, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool K2Node_Event_IsDesignTime, bool CallFunc_Greater_IntInt_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, class UWBP_Template_ProgressTrackerImage_C* CallFunc_Array_Get_Item, class UWidget* CallFunc_Array_Get_Item_1, class UWBP_Template_ProgressTrackerImage_C* K2Node_DynamicCast_AsWBP_Template_Progress_Tracker_Image, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, float K2Node_MakeStruct_Right_ImplicitCast);
	void PreConstruct(bool IsDesignTime);
	void SetActivePage(int32 Param_ActivePage, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UWBP_Template_ProgressTrackerImage_C* CallFunc_Array_Get_Item, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, double CallFunc_Divide_DoubleDouble_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_Divide_DoubleDouble_B_ImplicitCast, float CallFunc_SetPercent_InPercent_ImplicitCast);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Template_ProgressTracker_CM_C">();
	}
	static class UWBP_Template_ProgressTracker_CM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Template_ProgressTracker_CM_C>();
	}
};
static_assert(alignof(UWBP_Template_ProgressTracker_CM_C) == 0x000008, "Wrong alignment on UWBP_Template_ProgressTracker_CM_C");
static_assert(sizeof(UWBP_Template_ProgressTracker_CM_C) == 0x0002B8, "Wrong size on UWBP_Template_ProgressTracker_CM_C");
static_assert(offsetof(UWBP_Template_ProgressTracker_CM_C, UberGraphFrame) == 0x000278, "Member 'UWBP_Template_ProgressTracker_CM_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ProgressTracker_CM_C, HorizontalBox_TrackingImages) == 0x000280, "Member 'UWBP_Template_ProgressTracker_CM_C::HorizontalBox_TrackingImages' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ProgressTracker_CM_C, VALUI_ProgressBar_Styled_67) == 0x000288, "Member 'UWBP_Template_ProgressTracker_CM_C::VALUI_ProgressBar_Styled_67' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ProgressTracker_CM_C, MaxPages) == 0x000290, "Member 'UWBP_Template_ProgressTracker_CM_C::MaxPages' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ProgressTracker_CM_C, PageWidgets) == 0x000298, "Member 'UWBP_Template_ProgressTracker_CM_C::PageWidgets' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ProgressTracker_CM_C, ActivePage) == 0x0002A8, "Member 'UWBP_Template_ProgressTracker_CM_C::ActivePage' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ProgressTracker_CM_C, TrackerSpacing) == 0x0002B0, "Member 'UWBP_Template_ProgressTracker_CM_C::TrackerSpacing' has a wrong offset!");

}

