#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MinigameQTEInput2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MinigameQTEInput2.WBP_MinigameQTEInput2_C
// 0x0048 (0x02C0 - 0x0278)
class UWBP_MinigameQTEInput2_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Bar;                                               // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Window;                                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	double                                        StartTime;                                         // 0x0290(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Duration;                                          // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        StartX;                                            // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DeltaX;                                            // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        PositionY;                                         // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        EndTime;                                           // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MinigameQTEInput2(int32 EntryPoint);
	void ForcePosition(double NormalizedTime, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue);
	void HideWindow();
	void OnInitialized();
	void SetPositionByTime(double Time, bool CallFunc_Greater_DoubleDouble_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Divide_DoubleDouble_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue);
	void SetWindowSize(double WindowSize, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue);
	void Start(double Param_StartTime, double TargetTime, double Param_StartX, double TargetX, double Param_EndTime, double Param_PositionY, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_1, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MinigameQTEInput2_C">();
	}
	static class UWBP_MinigameQTEInput2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MinigameQTEInput2_C>();
	}
};
static_assert(alignof(UWBP_MinigameQTEInput2_C) == 0x000008, "Wrong alignment on UWBP_MinigameQTEInput2_C");
static_assert(sizeof(UWBP_MinigameQTEInput2_C) == 0x0002C0, "Wrong size on UWBP_MinigameQTEInput2_C");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, UberGraphFrame) == 0x000278, "Member 'UWBP_MinigameQTEInput2_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, Bar) == 0x000280, "Member 'UWBP_MinigameQTEInput2_C::Bar' has a wrong offset!");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, Window) == 0x000288, "Member 'UWBP_MinigameQTEInput2_C::Window' has a wrong offset!");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, StartTime) == 0x000290, "Member 'UWBP_MinigameQTEInput2_C::StartTime' has a wrong offset!");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, Duration) == 0x000298, "Member 'UWBP_MinigameQTEInput2_C::Duration' has a wrong offset!");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, StartX) == 0x0002A0, "Member 'UWBP_MinigameQTEInput2_C::StartX' has a wrong offset!");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, DeltaX) == 0x0002A8, "Member 'UWBP_MinigameQTEInput2_C::DeltaX' has a wrong offset!");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, PositionY) == 0x0002B0, "Member 'UWBP_MinigameQTEInput2_C::PositionY' has a wrong offset!");
static_assert(offsetof(UWBP_MinigameQTEInput2_C, EndTime) == 0x0002B8, "Member 'UWBP_MinigameQTEInput2_C::EndTime' has a wrong offset!");

}

