#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RichMarkupPhoto

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_RichMarkupPhoto.WBP_RichMarkupPhoto_C
// 0x0058 (0x02D0 - 0x0278)
class UWBP_RichMarkupPhoto_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USizeBox*                               Box_Overlays;                                      // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HBox_TaggedPlayers;                                // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_CapturedPhoto;                               // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             NamedSlot_Overlay;                                 // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FVector2D                              TaggedPlayerPortraitSize;                          // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FMargin                                InteriorPadding;                                   // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	TScriptInterface<class IVAL_RichMarkupPhotographInterface> Photo_Interface;                                   // 0x02C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_RichMarkupPhoto(int32 EntryPoint, int32 Temp_int_Array_Index_Variable, bool K2Node_Event_IsDesignTime, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UWBP_PlayerCharacterProfileImage_CM_C* CallFunc_Create_ReturnValue, class UHorizontalBoxSlot* CallFunc_AddChildToHorizontalBox_ReturnValue, class UPanelSlot* CallFunc_GetContentSlot_ReturnValue, class USizeBoxSlot* K2Node_DynamicCast_AsSize_Box_Slot, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TScriptInterface<class IVAL_RichMarkupPhotographInterface> K2Node_CustomEvent_PhotoInterface, int32 Temp_int_Variable, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, class UObject* CallFunc_Conv_InterfaceToObject_ReturnValue, const TSet<struct FUniqueNetIdRepl>& CallFunc_GetPlayersInPhotograph_ReturnValue, bool CallFunc_IsValid_ReturnValue, TArray<struct FUniqueNetIdRepl>& CallFunc_Set_ToArray_Result, const struct FUniqueNetIdRepl& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, class UWBP_PlayerCharacterProfileImage_CM_C* CallFunc_Create_ReturnValue_1, class UHorizontalBoxSlot* CallFunc_AddChildToHorizontalBox_ReturnValue_1);
	void PreConstruct(bool IsDesignTime);
	void RefreshImageFromPhoto(class UObject* CallFunc_GetPhotographImageResourceObject_ReturnValue, class UObject* CallFunc_Conv_InterfaceToObject_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void SetPhoto(TScriptInterface<class IVAL_RichMarkupPhotographInterface> PhotoInterface);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_RichMarkupPhoto_C">();
	}
	static class UWBP_RichMarkupPhoto_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RichMarkupPhoto_C>();
	}
};
static_assert(alignof(UWBP_RichMarkupPhoto_C) == 0x000008, "Wrong alignment on UWBP_RichMarkupPhoto_C");
static_assert(sizeof(UWBP_RichMarkupPhoto_C) == 0x0002D0, "Wrong size on UWBP_RichMarkupPhoto_C");
static_assert(offsetof(UWBP_RichMarkupPhoto_C, UberGraphFrame) == 0x000278, "Member 'UWBP_RichMarkupPhoto_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_RichMarkupPhoto_C, Box_Overlays) == 0x000280, "Member 'UWBP_RichMarkupPhoto_C::Box_Overlays' has a wrong offset!");
static_assert(offsetof(UWBP_RichMarkupPhoto_C, HBox_TaggedPlayers) == 0x000288, "Member 'UWBP_RichMarkupPhoto_C::HBox_TaggedPlayers' has a wrong offset!");
static_assert(offsetof(UWBP_RichMarkupPhoto_C, Image_CapturedPhoto) == 0x000290, "Member 'UWBP_RichMarkupPhoto_C::Image_CapturedPhoto' has a wrong offset!");
static_assert(offsetof(UWBP_RichMarkupPhoto_C, NamedSlot_Overlay) == 0x000298, "Member 'UWBP_RichMarkupPhoto_C::NamedSlot_Overlay' has a wrong offset!");
static_assert(offsetof(UWBP_RichMarkupPhoto_C, TaggedPlayerPortraitSize) == 0x0002A0, "Member 'UWBP_RichMarkupPhoto_C::TaggedPlayerPortraitSize' has a wrong offset!");
static_assert(offsetof(UWBP_RichMarkupPhoto_C, InteriorPadding) == 0x0002B0, "Member 'UWBP_RichMarkupPhoto_C::InteriorPadding' has a wrong offset!");
static_assert(offsetof(UWBP_RichMarkupPhoto_C, Photo_Interface) == 0x0002C0, "Member 'UWBP_RichMarkupPhoto_C::Photo_Interface' has a wrong offset!");

}

