#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Cooking_Minigame_RollingPin_GoalPost

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Cooking_Minigame_RollingPin_GoalPost.WBP_Cooking_Minigame_RollingPin_GoalPost_C
// 0x0028 (0x02A0 - 0x0278)
class UWBP_Cooking_Minigame_RollingPin_GoalPost_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       PlayError;                                         // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       PlaySuccess;                                       // 0x0288(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetSwitcher*                        Input_StateSwitcher;                               // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               TapTarget_Right;                                   // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_WBP_Cooking_Minigame_RollingPin_GoalPost(int32 EntryPoint);
	void Play_Error_Animation(class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue);
	void Play_Success_Animation(int32 CallFunc_AkEventGlobal_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue);
	void Reset();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Cooking_Minigame_RollingPin_GoalPost_C">();
	}
	static class UWBP_Cooking_Minigame_RollingPin_GoalPost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Cooking_Minigame_RollingPin_GoalPost_C>();
	}
};
static_assert(alignof(UWBP_Cooking_Minigame_RollingPin_GoalPost_C) == 0x000008, "Wrong alignment on UWBP_Cooking_Minigame_RollingPin_GoalPost_C");
static_assert(sizeof(UWBP_Cooking_Minigame_RollingPin_GoalPost_C) == 0x0002A0, "Wrong size on UWBP_Cooking_Minigame_RollingPin_GoalPost_C");
static_assert(offsetof(UWBP_Cooking_Minigame_RollingPin_GoalPost_C, UberGraphFrame) == 0x000278, "Member 'UWBP_Cooking_Minigame_RollingPin_GoalPost_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Minigame_RollingPin_GoalPost_C, PlayError) == 0x000280, "Member 'UWBP_Cooking_Minigame_RollingPin_GoalPost_C::PlayError' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Minigame_RollingPin_GoalPost_C, PlaySuccess) == 0x000288, "Member 'UWBP_Cooking_Minigame_RollingPin_GoalPost_C::PlaySuccess' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Minigame_RollingPin_GoalPost_C, Input_StateSwitcher) == 0x000290, "Member 'UWBP_Cooking_Minigame_RollingPin_GoalPost_C::Input_StateSwitcher' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Minigame_RollingPin_GoalPost_C, TapTarget_Right) == 0x000298, "Member 'UWBP_Cooking_Minigame_RollingPin_GoalPost_C::TapTarget_Right' has a wrong offset!");

}

