#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Template_ContextMenuAnchor_CM

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "CommonWidgetInputExtended_classes.hpp"
#include "CommonInput_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Template_ContextMenuAnchor_CM.WBP_Template_ContextMenuAnchor_CM_C
// 0x0060 (0x0540 - 0x04E0)
class UWBP_Template_ContextMenuAnchor_CM_C final  : public UCommonActivatableWidgetInputExtended
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMenuAnchor*                            MenuAnchor;                                        // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UClass*                                 MenuContentClass;                                  // 0x04F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            MenuContentWidget;                                 // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EMenuPlacement                                Placement;                                         // 0x0500(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          FitInWindow;                                       // 0x0501(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_444C[0x6];                                     // 0x0502(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnMenuContentCreated;                              // 0x0508(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnMenuClose;                                       // 0x0518(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bEnableCloseByLostFocus;                           // 0x0528(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_444D[0x7];                                     // 0x0529(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnMenuOpened;                                      // 0x0530(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__WBP_Template_ContextMenuAnchor_MenuAnchor_K2Node_ComponentBoundEvent_0_OnMenuOpenChangedEvent__DelegateSignature(bool bIsOpen);
	void Close(bool bCloseByLostFocus);
	void Construct();
	void ExecuteUbergraph_WBP_Template_ContextMenuAnchor_CM(int32 EntryPoint, const struct FInputActionValue& K2Node_EnhancedInputActionEvent_ActionValue, float K2Node_EnhancedInputActionEvent_ElapsedTime, float K2Node_EnhancedInputActionEvent_TriggeredTime, class UInputAction* K2Node_EnhancedInputActionEvent_SourceAction, class UInputAction* Temp_object_Variable, bool CallFunc_Conv_InputActionValueToBool_ReturnValue, double Temp_real_Variable, double Temp_real_Variable_1, double Temp_real_Variable_0, double Temp_real_Variable_1_0, bool Temp_bool_Variable, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, bool K2Node_ComponentBoundEvent_bIsOpen, bool CallFunc_IsValid_ReturnValue, bool K2Node_Event_IsDesignTime, bool CallFunc_IsOpen_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class UCommonInputSubsystem* CallFunc_GetLocalPlayerSubsystem_ReturnValue, class UCommonInputSubsystem* CallFunc_GetLocalPlayerSubsystem_ReturnValue_1, bool CallFunc_IsInputMethodActive_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_HasFocusedDescendants_ReturnValue, bool CallFunc_HasAnyUserFocus_ReturnValue, TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate, ECommonInputType K2Node_CustomEvent_bNewInputType, bool K2Node_SwitchEnum_CmpSuccess);
	class UUserWidget* HandleMenuAnchorGetUserMenuContent(bool CallFunc_IsValid_ReturnValue, class UClass* CallFunc_GetObjectClass_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue, class UUserWidget* CallFunc_Create_ReturnValue);
	void InpActEvt_IA_UI_Back_Cancel_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, class UInputAction* SourceAction);
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent, const struct FEventReply& CallFunc_Handled_ReturnValue);
	void OnInputMethodChanged(ECommonInputType bNewInputType);
	void OnMenuClose__DelegateSignature(bool bClosedByLostFocus);
	void OnMenuContentCreated__DelegateSignature(class UUserWidget* MenuContent);
	void OnMenuOpened__DelegateSignature(class UUserWidget* MenuContent);
	void Open(bool bFocusMenu);
	void PreConstruct(bool IsDesignTime);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Template_ContextMenuAnchor_CM_C">();
	}
	static class UWBP_Template_ContextMenuAnchor_CM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Template_ContextMenuAnchor_CM_C>();
	}
};
static_assert(alignof(UWBP_Template_ContextMenuAnchor_CM_C) == 0x000008, "Wrong alignment on UWBP_Template_ContextMenuAnchor_CM_C");
static_assert(sizeof(UWBP_Template_ContextMenuAnchor_CM_C) == 0x000540, "Wrong size on UWBP_Template_ContextMenuAnchor_CM_C");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, UberGraphFrame) == 0x0004E0, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, MenuAnchor) == 0x0004E8, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::MenuAnchor' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, MenuContentClass) == 0x0004F0, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::MenuContentClass' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, MenuContentWidget) == 0x0004F8, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::MenuContentWidget' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, Placement) == 0x000500, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::Placement' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, FitInWindow) == 0x000501, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::FitInWindow' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, OnMenuContentCreated) == 0x000508, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::OnMenuContentCreated' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, OnMenuClose) == 0x000518, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::OnMenuClose' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, bEnableCloseByLostFocus) == 0x000528, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::bEnableCloseByLostFocus' has a wrong offset!");
static_assert(offsetof(UWBP_Template_ContextMenuAnchor_CM_C, OnMenuOpened) == 0x000530, "Member 'UWBP_Template_ContextMenuAnchor_CM_C::OnMenuOpened' has a wrong offset!");

}

