#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Dynamic2DDropShadow

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Dynamic2DDropShadow.WBP_Dynamic2DDropShadow_C
// 0x0108 (0x0380 - 0x0278)
class UWBP_Dynamic2DDropShadow_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image;                                             // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint8                                         Pad_4AC0[0x8];                                     // 0x0288(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            Brush;                                             // 0x0290(0x00D0)(Edit, BlueprintVisible, ExposeOnSpawn)
	class UMaterialInstanceDynamic*               MI_DropShadow;                                     // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             CurrentTexture;                                    // 0x0368(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstance*                      MI_Shadow;                                         // 0x0370(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Dynamic2DDropShadow(int32 EntryPoint, bool CallFunc_IsValid_ReturnValue, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, bool K2Node_Event_IsDesignTime, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, const struct FSlateBrush& K2Node_Copy_ReturnValue, class UTexture2D* K2Node_DynamicCast_AsTexture_2D, bool K2Node_DynamicCast_bSuccess, const struct FSlateBrush& K2Node_SetFieldsInStruct_StructOut, TSoftObjectPtr<class UTexture2D> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue);
	void PreConstruct(bool IsDesignTime);
	void SetImageTexture(TSoftObjectPtr<class UTexture2D> NewSoftTexture, class UObject* CallFunc_LoadAsset_Blocking_ReturnValue, class UTexture2D* K2Node_DynamicCast_AsTexture_2D, bool K2Node_DynamicCast_bSuccess);
	void SetShadowTexture(class UTexture* Texture);
	void UpdateDropShadow(class UTexture2D* K2Node_DynamicCast_AsTexture_2D, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, const struct FSlateBrush& K2Node_MakeStruct_SlateBrush);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Dynamic2DDropShadow_C">();
	}
	static class UWBP_Dynamic2DDropShadow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Dynamic2DDropShadow_C>();
	}
};
static_assert(alignof(UWBP_Dynamic2DDropShadow_C) == 0x000010, "Wrong alignment on UWBP_Dynamic2DDropShadow_C");
static_assert(sizeof(UWBP_Dynamic2DDropShadow_C) == 0x000380, "Wrong size on UWBP_Dynamic2DDropShadow_C");
static_assert(offsetof(UWBP_Dynamic2DDropShadow_C, UberGraphFrame) == 0x000278, "Member 'UWBP_Dynamic2DDropShadow_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Dynamic2DDropShadow_C, Image) == 0x000280, "Member 'UWBP_Dynamic2DDropShadow_C::Image' has a wrong offset!");
static_assert(offsetof(UWBP_Dynamic2DDropShadow_C, Brush) == 0x000290, "Member 'UWBP_Dynamic2DDropShadow_C::Brush' has a wrong offset!");
static_assert(offsetof(UWBP_Dynamic2DDropShadow_C, MI_DropShadow) == 0x000360, "Member 'UWBP_Dynamic2DDropShadow_C::MI_DropShadow' has a wrong offset!");
static_assert(offsetof(UWBP_Dynamic2DDropShadow_C, CurrentTexture) == 0x000368, "Member 'UWBP_Dynamic2DDropShadow_C::CurrentTexture' has a wrong offset!");
static_assert(offsetof(UWBP_Dynamic2DDropShadow_C, MI_Shadow) == 0x000370, "Member 'UWBP_Dynamic2DDropShadow_C::MI_Shadow' has a wrong offset!");

}

