#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Cooking_Hud_Shelved_PF

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Cooking_Hud_Shelved_PF.WBP_Cooking_Hud_Shelved_PF_C
// 0x0050 (0x02C8 - 0x0278)
class UWBP_Cooking_Hud_Shelved_PF_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       HideHud;                                           // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ShowHUD;                                           // 0x0288(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UOverlay*                               Icon_ItemsShelved;                                 // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_108;                                         // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_KnifeBackground;                             // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         IngredientsBox;                                    // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCrafterComponent*                      ComplexCrafter;                                    // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          PartOfRecipe;                                      // 0x02B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4DF1[0x7];                                     // 0x02B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AValeriaCharacter*                      ValeriaCharacter;                                  // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Cooking_Hud_Shelved_PF(int32 EntryPoint, bool K2Node_Event_IsDesignTime);
	void Handle_Ingredient_Shelf_Changed(struct FComplexRecipeRecord& RecipeRecord, const TArray<bool>& StarQuality, const TArray<int32>& ShelfIngredientCounts, const TArray<class UTexture2D*>& ShelfIngredientIcons, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, const struct FComplexRecipeIngredientSet& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, bool Temp_bool_Variable, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Greater_IntInt_ReturnValue_1, class UWidget* CallFunc_GetChildAt_ReturnValue, class UWBP_Cooking_ShelvedIngredient_C* K2Node_DynamicCast_AsWBP_Cooking_Shelved_Ingredient, bool K2Node_DynamicCast_bSuccess, ESlateVisibility K2Node_Select_Default, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, class UTexture2D* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue_2);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Cooking_Hud_Shelved_PF_C">();
	}
	static class UWBP_Cooking_Hud_Shelved_PF_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Cooking_Hud_Shelved_PF_C>();
	}
};
static_assert(alignof(UWBP_Cooking_Hud_Shelved_PF_C) == 0x000008, "Wrong alignment on UWBP_Cooking_Hud_Shelved_PF_C");
static_assert(sizeof(UWBP_Cooking_Hud_Shelved_PF_C) == 0x0002C8, "Wrong size on UWBP_Cooking_Hud_Shelved_PF_C");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, UberGraphFrame) == 0x000278, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, HideHud) == 0x000280, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::HideHud' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, ShowHUD) == 0x000288, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::ShowHUD' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, Icon_ItemsShelved) == 0x000290, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::Icon_ItemsShelved' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, Image_108) == 0x000298, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::Image_108' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, Image_KnifeBackground) == 0x0002A0, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::Image_KnifeBackground' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, IngredientsBox) == 0x0002A8, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::IngredientsBox' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, ComplexCrafter) == 0x0002B0, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::ComplexCrafter' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, PartOfRecipe) == 0x0002B8, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::PartOfRecipe' has a wrong offset!");
static_assert(offsetof(UWBP_Cooking_Hud_Shelved_PF_C, ValeriaCharacter) == 0x0002C0, "Member 'UWBP_Cooking_Hud_Shelved_PF_C::ValeriaCharacter' has a wrong offset!");

}

