#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Template_PopupMain_02

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Template_PopupMain_02.WBP_Template_PopupMain_02_C
// 0x0090 (0x0308 - 0x0278)
class UWBP_Template_PopupMain_02_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Backer_HeaderBackground;                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Backer_HeaderPattern;                              // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_514;                                         // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             NamedSlot_Content;                                 // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             NamedSlot_Tabs;                                    // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVALUI_TextBlock_Styled*                TextBlock_Header;                                  // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CloseButton_CM_C*                  WBP_CloseButton_CM;                                // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             CloseButton_OnClicked;                             // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FMargin                                ContentPadding;                                    // 0x02C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	EVerticalAlignment                            VAlign_Content;                                    // 0x02D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          HAlign_Content;                                    // 0x02D9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E6E[0x6];                                     // 0x02DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   HeaderText;                                        // 0x02E0(0x0018)(Edit, BlueprintVisible)
	struct FMargin                                TabPadding;                                        // 0x02F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void BndEvt__WBP_Template_PopupMain_02_WBP_CloseButton_CM_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature();
	void CloseButton_OnClicked__DelegateSignature();
	void ExecuteUbergraph_WBP_Template_PopupMain_02(int32 EntryPoint, bool K2Node_Event_IsDesignTime);
	void PreConstruct(bool IsDesignTime);
	void SetContentSettings(const struct FMargin& Param_ContentPadding, EVerticalAlignment Param_VAlign_Content, EHorizontalAlignment Param_HAlign_Content, class UOverlaySlot* CallFunc_SlotAsOverlaySlot_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void SetHeaderText(class FText Param_HeaderText);
	void SetTabSettings(const struct FMargin& Param_TabPadding, class UOverlaySlot* CallFunc_SlotAsOverlaySlot_ReturnValue, bool CallFunc_IsValid_ReturnValue);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Template_PopupMain_02_C">();
	}
	static class UWBP_Template_PopupMain_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Template_PopupMain_02_C>();
	}
};
static_assert(alignof(UWBP_Template_PopupMain_02_C) == 0x000008, "Wrong alignment on UWBP_Template_PopupMain_02_C");
static_assert(sizeof(UWBP_Template_PopupMain_02_C) == 0x000308, "Wrong size on UWBP_Template_PopupMain_02_C");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, UberGraphFrame) == 0x000278, "Member 'UWBP_Template_PopupMain_02_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, Backer_HeaderBackground) == 0x000280, "Member 'UWBP_Template_PopupMain_02_C::Backer_HeaderBackground' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, Backer_HeaderPattern) == 0x000288, "Member 'UWBP_Template_PopupMain_02_C::Backer_HeaderPattern' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, Image_514) == 0x000290, "Member 'UWBP_Template_PopupMain_02_C::Image_514' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, NamedSlot_Content) == 0x000298, "Member 'UWBP_Template_PopupMain_02_C::NamedSlot_Content' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, NamedSlot_Tabs) == 0x0002A0, "Member 'UWBP_Template_PopupMain_02_C::NamedSlot_Tabs' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, TextBlock_Header) == 0x0002A8, "Member 'UWBP_Template_PopupMain_02_C::TextBlock_Header' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, WBP_CloseButton_CM) == 0x0002B0, "Member 'UWBP_Template_PopupMain_02_C::WBP_CloseButton_CM' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, CloseButton_OnClicked) == 0x0002B8, "Member 'UWBP_Template_PopupMain_02_C::CloseButton_OnClicked' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, ContentPadding) == 0x0002C8, "Member 'UWBP_Template_PopupMain_02_C::ContentPadding' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, VAlign_Content) == 0x0002D8, "Member 'UWBP_Template_PopupMain_02_C::VAlign_Content' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, HAlign_Content) == 0x0002D9, "Member 'UWBP_Template_PopupMain_02_C::HAlign_Content' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, HeaderText) == 0x0002E0, "Member 'UWBP_Template_PopupMain_02_C::HeaderText' has a wrong offset!");
static_assert(offsetof(UWBP_Template_PopupMain_02_C, TabPadding) == 0x0002F8, "Member 'UWBP_Template_PopupMain_02_C::TabPadding' has a wrong offset!");

}

