#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IconButton_CM

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_IconButton_CM.WBP_IconButton_CM_C
// 0x0020 (0x1510 - 0x14F0)
class UWBP_IconButton_CM_C final  : public UCommonButtonBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x14F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 IconImage;                                         // 0x14F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTexture2D*                             IconTexture;                                       // 0x1500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_IconButton_CM(int32 EntryPoint, bool K2Node_Event_IsDesignTime);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_IconButton_CM_C">();
	}
	static class UWBP_IconButton_CM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_IconButton_CM_C>();
	}
};
static_assert(alignof(UWBP_IconButton_CM_C) == 0x000010, "Wrong alignment on UWBP_IconButton_CM_C");
static_assert(sizeof(UWBP_IconButton_CM_C) == 0x001510, "Wrong size on UWBP_IconButton_CM_C");
static_assert(offsetof(UWBP_IconButton_CM_C, UberGraphFrame) == 0x0014F0, "Member 'UWBP_IconButton_CM_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_IconButton_CM_C, IconImage) == 0x0014F8, "Member 'UWBP_IconButton_CM_C::IconImage' has a wrong offset!");
static_assert(offsetof(UWBP_IconButton_CM_C, IconTexture) == 0x001500, "Member 'UWBP_IconButton_CM_C::IconTexture' has a wrong offset!");

}

