#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PinnedQuestGoal

#include "Basic.hpp"

#include "Palia_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_PinnedQuestGoal.WBP_PinnedQuestGoal_C.ExecuteUbergraph_WBP_PinnedQuestGoal
// 0x0008 (0x0008 - 0x0000)
struct WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal final 
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsConsole_ReturnValue;                    // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal) == 0x000004, "Wrong alignment on WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal");
static_assert(sizeof(WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal) == 0x000008, "Wrong size on WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal");
static_assert(offsetof(WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal, EntryPoint) == 0x000000, "Member 'WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal, CallFunc_IsConsole_ReturnValue) == 0x000005, "Member 'WBP_PinnedQuestGoal_C_ExecuteUbergraph_WBP_PinnedQuestGoal::CallFunc_IsConsole_ReturnValue' has a wrong offset!");

// Function WBP_PinnedQuestGoal.WBP_PinnedQuestGoal_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_PinnedQuestGoal_C_PreConstruct final 
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PinnedQuestGoal_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_PinnedQuestGoal_C_PreConstruct");
static_assert(sizeof(WBP_PinnedQuestGoal_C_PreConstruct) == 0x000001, "Wrong size on WBP_PinnedQuestGoal_C_PreConstruct");
static_assert(offsetof(WBP_PinnedQuestGoal_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_PinnedQuestGoal_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_PinnedQuestGoal.WBP_PinnedQuestGoal_C.SetFromDescriptionText
// 0x0018 (0x0018 - 0x0000)
struct WBP_PinnedQuestGoal_C_SetFromDescriptionText final 
{
public:
	class FText                                   Description;                                       // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_PinnedQuestGoal_C_SetFromDescriptionText) == 0x000008, "Wrong alignment on WBP_PinnedQuestGoal_C_SetFromDescriptionText");
static_assert(sizeof(WBP_PinnedQuestGoal_C_SetFromDescriptionText) == 0x000018, "Wrong size on WBP_PinnedQuestGoal_C_SetFromDescriptionText");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromDescriptionText, Description) == 0x000000, "Member 'WBP_PinnedQuestGoal_C_SetFromDescriptionText::Description' has a wrong offset!");

// Function WBP_PinnedQuestGoal.WBP_PinnedQuestGoal_C.SetFromQuestGoalState
// 0x0140 (0x0140 - 0x0000)
struct WBP_PinnedQuestGoal_C_SetFromQuestGoalState final 
{
public:
	struct FVAL_QuestGoalState                    QuestGoalState;                                    // 0x0000(0x0070)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FVAL_QuestGoalDef                      QuestGoalDef;                                      // 0x0070(0x0058)(BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
	bool                                          IsBranchingGoal;                                   // 0x00C8(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVAL_QuestBranchingGoalChoiceStatus           ChoiceStatus;                                      // 0x00C9(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00CA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00CB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EValeriaFuncResult                            CallFunc_GetValeriaCharacter_OutResult;            // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46CC[0x3];                                     // 0x00CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AValeriaCharacter*                      CallFunc_GetValeriaCharacter_ReturnValue;          // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetQuestGoalDescription_ReturnValue;      // 0x00D8(0x0018)()
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46CD[0x7];                                     // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_PerformTextSubstitutionsForCharacter_ReturnValue; // 0x00F8(0x0018)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0110(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0120(0x0018)()
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0139(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x013A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x013B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState) == 0x000008, "Wrong alignment on WBP_PinnedQuestGoal_C_SetFromQuestGoalState");
static_assert(sizeof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState) == 0x000140, "Wrong size on WBP_PinnedQuestGoal_C_SetFromQuestGoalState");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, QuestGoalState) == 0x000000, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::QuestGoalState' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, QuestGoalDef) == 0x000070, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::QuestGoalDef' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, IsBranchingGoal) == 0x0000C8, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::IsBranchingGoal' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, ChoiceStatus) == 0x0000C9, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::ChoiceStatus' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000CA, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, CallFunc_BooleanAND_ReturnValue) == 0x0000CB, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, CallFunc_GetValeriaCharacter_OutResult) == 0x0000CC, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::CallFunc_GetValeriaCharacter_OutResult' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, CallFunc_GetValeriaCharacter_ReturnValue) == 0x0000D0, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::CallFunc_GetValeriaCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, CallFunc_GetQuestGoalDescription_ReturnValue) == 0x0000D8, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::CallFunc_GetQuestGoalDescription_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, K2Node_SwitchEnum_CmpSuccess) == 0x0000F0, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, CallFunc_PerformTextSubstitutionsForCharacter_ReturnValue) == 0x0000F8, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::CallFunc_PerformTextSubstitutionsForCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, K2Node_MakeArray_Array) == 0x000110, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, CallFunc_Format_ReturnValue) == 0x000120, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, Temp_byte_Variable) == 0x000138, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, Temp_byte_Variable_1) == 0x000139, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, Temp_bool_Variable) == 0x00013A, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PinnedQuestGoal_C_SetFromQuestGoalState, K2Node_Select_Default) == 0x00013B, "Member 'WBP_PinnedQuestGoal_C_SetFromQuestGoalState::K2Node_Select_Default' has a wrong offset!");

}

