#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HealthBar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_HealthBar.WBP_HealthBar_C
// 0x0028 (0x02A0 - 0x0278)
class UWBP_HealthBar_C : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeOut;                                           // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_37;                                    // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class AActor*                                 Actor;                                             // 0x0290(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowStartAsMax;                                    // 0x0298(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BindOnChanged(class UVitalsComponent*& Vitals);
	void ExecuteUbergraph_WBP_HealthBar(int32 EntryPoint, class UVitalsComponent* K2Node_CustomEvent_Vitals, TDelegate<void(class UVitalsComponent* Vitals)> K2Node_CreateDelegate_OutputDelegate, class UVitalsComponent* K2Node_CustomEvent_Vitals_1);
	void OnChanged(class UVitalsComponent* Vitals);
	void SetActor(class AActor*& Param_Actor, class UVitalsComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void Update(class UVitalsComponent*& VitalsComponent, bool Temp_bool_Variable, uint8 CallFunc_MakeLiteralByte_ReturnValue, int32 CallFunc_GetVitalStart_ReturnValue, int32 CallFunc_GetVital_ReturnValue, int32 CallFunc_GetVitalMax_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, int32 K2Node_Select_Default, float CallFunc_Conv_IntToFloat_ReturnValue_1, double CallFunc_Divide_DoubleDouble_ReturnValue, double CallFunc_FClamp_ReturnValue, double CallFunc_Divide_DoubleDouble_A_ImplicitCast, double CallFunc_Divide_DoubleDouble_B_ImplicitCast, float CallFunc_SetPercent_InPercent_ImplicitCast);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_HealthBar_C">();
	}
	static class UWBP_HealthBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_HealthBar_C>();
	}
};
static_assert(alignof(UWBP_HealthBar_C) == 0x000008, "Wrong alignment on UWBP_HealthBar_C");
static_assert(sizeof(UWBP_HealthBar_C) == 0x0002A0, "Wrong size on UWBP_HealthBar_C");
static_assert(offsetof(UWBP_HealthBar_C, UberGraphFrame) == 0x000278, "Member 'UWBP_HealthBar_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_HealthBar_C, FadeOut) == 0x000280, "Member 'UWBP_HealthBar_C::FadeOut' has a wrong offset!");
static_assert(offsetof(UWBP_HealthBar_C, ProgressBar_37) == 0x000288, "Member 'UWBP_HealthBar_C::ProgressBar_37' has a wrong offset!");
static_assert(offsetof(UWBP_HealthBar_C, Actor) == 0x000290, "Member 'UWBP_HealthBar_C::Actor' has a wrong offset!");
static_assert(offsetof(UWBP_HealthBar_C, ShowStartAsMax) == 0x000298, "Member 'UWBP_HealthBar_C::ShowStartAsMax' has a wrong offset!");

}

